project:
  type: book
  output-dir: docs
  render:
    - "index.qmd"
    - "material/00_intro/intro.qmd"
    - "material/01_github/*.qmd"
    - "material/02_colab/*.qmd"
    - "material/03_latex/*.qmd"
    - "material/04_quarto/*.qmd"
    - "material/05_ia/*.qmd"

book:
  title: "Docencia Digital"
  subtitle: "Ecosistema digital para el académico del siglo XXI"
  author: "Francisco Alfaro"
  date: "06/01/2026"
  favicon: "assets/img/brand/brand__usm.png"
  repo-url: "https://github.com/fralfaro/docencia-digital"
  sidebar:
    logo: "assets/img/brand/brand__usm.png"

  chapters:
    - index.qmd
    - part: "🟪 Introducción"
      chapters:
        - material/00_intro/intro.qmd
    - part: material/01_github/index.qmd  # <-- archivo, no texto
      chapters:
        - material/01_github/01_esencial.qmd
        - material/01_github/02_colaborativo.qmd
        - material/01_github/03_automatizacion.qmd
    - part: material/02_colab/index.qmd  # <-- archivo, no texto
      chapters:
        - material/02_colab/colab_01_esencial.qmd
        - material/02_colab/colab_02_pandas.qmd
        - material/02_colab/colab_03_visualizacion.qmd
    - part: material/03_latex/index.qmd  # <-- archivo, no texto
      chapters:
        - material/03_latex/overleaf_01_esencial.qmd
        - material/03_latex/overleaf_02_matematica.qmd
        - material/03_latex/overleaf_03_plantillas.qmd
    - part: material/04_quarto/index.qmd  # <-- archivo, no texto
      chapters:
        - material/04_quarto/quarto_01_intro.qmd
        - material/04_quarto/quarto_02_documentos.qmd
        - material/04_quarto/quarto_03_revealjs.qmd
        - material/04_quarto/quarto_04_sitios.qmd
        - material/04_quarto/quarto_05_pages.qmd
        - material/04_quarto/quarto_06_flujo.qmd
    - part: material/05_ia/index.qmd  # <-- archivo, no texto
      chapters:
        - material/05_ia/ia_01_panorama.qmd
        - material/05_ia/ia_02_prompting.qmd
        - material/05_ia/ia_03_notebooklm.qmd
        - material/05_ia/ia_04_pedagogico.qmd
        - material/05_ia/ia_05_rag.qmd
        - material/05_ia/ia_06_agentes.qmd
        - material/05_ia/ia_07_copilot_studio.qmd
        - material/05_ia/ia_08_etica.qmd

lang: es

format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    number-sections: false
    toc: true
    page-layout: full