project:
  type: website

website:
  title: "USM"
  site-url: "https://sethnut.com/CEEMAT_2025/"
  favicon: 'images/usm.png'
  image: 'images/usm.png'
  page-footer:
    left: "Website creado con [Quarto](https://quarto.org/) por Francisco Alfaro. Licencia: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: linkedin
        href: https://www.linkedin.com/school/usantamaria/
      - icon: globe
        href: https://usm.cl/

  navbar:
    logo: /images/usm.png
    
    left:
      - text: Encuestas
        menu:
          - text: Encuesta 1° Semestre
            href: https://docs.google.com/forms/d/e/1FAIpQLSeCUqQw0LQxeBDcN15RSLE_Hetv0sffxaZOAagQCR0RkQHVHQ/viewform?usp=dialog
          - text: Encuesta 2° Semestre
            href: https://docs.google.com/forms/d/e/1FAIpQLSfD7Uw--mmOWrSJJuwVWdzJ8-1FUJhMwxeUlBWMk4rFvmloiQ/viewform?usp=dialog

      - text: Anexos
        menu:
          - text: Anexos
            href: anexos.html
     

    right:
      - icon: linkedin
        href: https://www.linkedin.com/school/usantamaria/
      - icon: globe
        href: https://usm.cl/


lang: es

format:
  html:
    smooth-scroll: true
    theme:
      - pulse
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true


editor: visual

comments:
  giscus:
    repo: Seth-Nut/CEEMAT_2025

execute:
  freeze: true

filters:
  - webr
  - pyodide